SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_KEY
FROM information_schema.COLUMNS 
WHERE TABLE_SCHEMA = 'temco_system' 
AND TABLE_NAME LIKE '%user%'
ORDER BY TABLE_NAME, ORDINAL_POSITION;
