FROM quay.io/wildfly/wildfly:31.0.0.Final-jdk17

# Add MariaDB driver
ADD --chown=jboss:jboss https://repo1.maven.org/maven2/org/mariadb/jdbc/mariadb-java-client/3.3.2/mariadb-java-client-3.3.2.jar /opt/jboss/wildfly/standalone/deployments/

# Copy standalone configuration
COPY standalone.xml /opt/jboss/wildfly/standalone/configuration/standalone.xml

# Expose ports
EXPOSE 8080 9990

# Start WildFly in standalone mode
CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]
